[theme]
primaryColor = ""  # Cor principal
backgroundColor = "#1A1A19"  # Cor de fundo
secondaryBackgroundColor = "#1A1A19"  # Cor de fundo secundária
textColor = "#F6FCDF"  # Cor do texto
font = "sans serif"  # Fonte